language: python

cache:
  pip: true
  directories:
  - chalice/.chalice/venv
  - daemons/dss-sync/.chalice/venv
  - daemons/dss-index/.chalice/venv

python: 3.6

dist: trusty

addons:
  apt:
    packages:
    - jq
    - moreutils
    - gettext

install:
- pip install -r requirements-dev.txt
- wget -q ${ES_DOWNLOAD_URL}
- tar -xzf elasticsearch-${ES_VERSION}.tar.gz
- wget -q http://us-east-1.ec2.archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.1-6_amd64.deb
- mkdir make4
- dpkg -x make*.deb make4
- export PATH=$(pwd)/make4/usr/bin:$PATH

before_script:
- export -n _JAVA_OPTIONS # https://github.com/travis-ci/travis-ci/issues/8408
- source environment

script:
- make $MAKE_ARGS

after_success:
- bash <(curl -s https://codecov.io/bash)

if: tag IS blank # don't build tags

stages:
- name: test
  if: env(TRAVIS_DSS_INTEGRATION_MODE) != 1
- name: integration_test
  if: env(TRAVIS_DSS_INTEGRATION_MODE) = 1
- name: deploy
  if: env(TRAVIS_DSS_INTEGRATION_MODE) != 1 AND branch IN (staging) AND type != pull_request

jobs:
  include:
  - stage: test
    env:
    - MAKE_ARGS="-j4 parallel_test"
  - stage: test
    env:
    - MAKE_ARGS="-j1 tests/test_search.py"
  - stage: test
    env:
    - MAKE_ARGS="-j1 tests/test_indexer.py"
    - DSS_UNITTEST_OPTS="-v TestAWSIndexer"
  - stage: test
    env:
    - MAKE_ARGS="-j1 tests/test_indexer.py"
    - DSS_UNITTEST_OPTS="-v TestGCPIndexer"
  - stage: test
    env:
    - MAKE_ARGS="-j1 tests/test_subscriptions.py"
  - stage: integration_test
    env:
    - MAKE_ARGS="-j1 integration_test"
  - stage: deploy
    script:
    - if [[ -f "environment.$TRAVIS_BRANCH" ]]; then source "environment.$TRAVIS_BRANCH"; fi
    deploy:
      provider: script
      script: make deploy
      skip_cleanup: true
      on:
        all_branches: true  # but see the `if:` conditional on the deploy stage above

env:
  global:
  - ES_VERSION=5.4.2
  - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - DSS_TEST_ES_PATH=./elasticsearch-${ES_VERSION}/bin/elasticsearch
  - DSS_ES_TIMEOUT=30
  - DSS_UNITTEST_OPTS="-v"
